export interface CalendarMonthData {
  month: string;
  events: { day: string; description: string; type: 'holiday' | 'event' | 'recess' }[];
}

export const calendarData: CalendarMonthData[] = [
  {
    month: "Febrero",
    events: [
      { day: "28", description: "Fiesta de la Ruptura del Ayuno del Sagrado Mes de Ramadán (Solo para habitantes que profesen la Religión Islámica)", type: "holiday" },
    ],
  },
  {
    month: "Marzo",
    events: [
      { day: "3-4", description: "Carnaval", type: "holiday" },
      { day: "5", description: "Inicio del Ciclo Lectivo", type: "event" },
      { day: "7", description: "Jornada de reflexión por el Día Internacional de la Mujer", type: "event" },
      { day: "12", description: "Día del Escudo Nacional", type: "event" },
      { day: "17", description: "Iniciación del Ciclo Lectivo de Formación Profesional", type: "event" },
      { day: "17-21", description: "Semana de reflexión en relación al Golpe de Estado perpetrado el 24 de marzo de 1976", type: "event" },
      { day: "21", description: "Día Nacional de la Memoria por la Verdad y la Justicia (24-3)", type: "event" },
      { day: "21", description: "Día Mundial de la Poesía", type: "event" },
      { day: "21", description: "Día Mundial del Agua", type: "event" },
      { day: "24", description: "Día Nacional de la Memoria por la Verdad y la Justicia", type: "holiday" },
      { day: "25-28", description: "Primera Semana de la Convivencia Escolar", type: "event" },
      { day: "26", description: "Día del Mercosur", type: "event" },
      { day: "27", description: "Día Mundial del Teatro", type: "event" },
      { day: "31", description: "Jornada de reflexión en homenaje a las víctimas de la tragedia ocorrida en la 'República de Cromañón'", type: "event" },
      { day: "31", description: "Día de la Hermandad Latinoamericana (2-4)", type: "event" },
    ],
  },
  {
    month: "Abril",
    events: [
      { day: "1", description: "Día Nacional de Concienciación sobre el Autismo (2-4)", type: "event" },
      { day: "2", description: "Día del Veterano y de los Caídos en la Guerra de Malvinas", type: "holiday" },
      { day: "3", description: "Jornada de Reflexión por Día del Veterano y de los Caídos en la Guerra de Malvinas", type: "event" },
      { day: "10", description: "Día de la Ciencia y de la Técnica", type: "event" },
      { day: "14", description: "Día de las Américas", type: "event" },
      { day: "14", description: "Día de la Constitución Provincial", type: "event" },
      { day: "16", description: "Día del Aborigen Americano (19-4)", type: "event" },
      { day: "16", description: "Día de la convivencia en la diversidad cultural (19-4)", type: "event" },
      { day: "17", description: "Jueves Santo", type: "holiday" },
      { day: "18", description: "Viernes Santo", type: "holiday" },
      { day: "21-25", description: "Semana de la Lectura", type: "event" },
      { day: "22", description: "40° aniversario del inicio del Juicio a las Juntas", type: "event" },
      { day: "22", description: "Día Internacional de la Madre Tierra", type: "event" },
      { day: "23", description: "Jornada de concientización en el marco de la Semana de la Vacunación en las Américas", type: "event" },
      { day: "24", description: "Día de acción por la tolerancia y el respeto entre los pueblos", type: "event" },
      { day: "24", description: "Día Internacional de las Niñas en las TIC", type: "event" },
      { day: "29", description: "Día Internacional de la Danza", type: "event" },
      { day: "29", description: "Día del Animal", type: "event" },
      { day: "30", description: "Día de las trabajadoras y los trabajadores (1-5)", type: "event" },
    ],
  },
  {
    month: "Mayo",
    events: [
      { day: "1", description: "Día de las trabajadoras y los trabajadores", type: "holiday" },
      { day: "2", description: "Día no laborable con fines turísticos", type: "holiday" },
      { day: "5", description: "Día de la Constitución Nacional (1-5)", type: "event" },
      { day: "5", description: "Promesa de Lealtad a la Constitución Nacional", type: "event" },
      { day: "5", description: "Día de los Heroicos Tripulantes del ARA General Belgrano (2-5)", type: "event" },
      { day: "5", description: "Día Internacional contra el Acoso Escolar (2-5)", type: "event" },
      { day: "6-9", description: "Semana de las matemáticas", type: "event" },
      { day: "7", description: "Día de la Minería", type: "event" },
      { day: "8", description: "Día Mundial de la Cruz Roja", type: "event" },
      { day: "8", description: "Día de Nuestra Señora de Luján", type: "event" },
      { day: "8", description: "Día Nacional de la Lucha contra la Violencia Institucional", type: "event" },
      { day: "9", description: "Día del Himno Nacional (11-5)", type: "event" },
      { day: "13", description: "Día del Escritor Bonaerense", type: "event" },
      { day: "16", description: "Día de la Armada Nacional (17-5)", type: "event" },
      { day: "16", description: "Día de la Escarapela (18-5)", type: "event" },
      { day: "19", description: "Día internacional contra la Discriminación por Orientación Sexual e Identidad de Género (17-05)", type: "event" },
      { day: "19-23", description: "Semana de la Historia Argentina", type: "event" },
      { day: "26", description: "Aniversario del Día de la Revolución de Mayo", type: "event" },
      { day: "27", description: "Día de la prevención de la violencia en el noviazgo", type: "event" },
      { day: "29", description: "Día del Ejército", type: "event" },
      { day: "30", description: "Primera Jornada Leer en Comunidad", type: "event" },
      { day: "30", description: "Día Nacional de la Donación de Órganos y Tejidos", type: "event" },
      { day: "30", description: "Día Mundial sin Tabaco (31-5)", type: "event" },
      { day: "30", description: "Celebración del Acuerdo de San Nicolás de los Arroyos (31-5)", type: "event" },
    ],
  },
  {
    month: "Junio",
    events: [
      { day: "2-6", description: "Semana de Convivencia Digital", type: "event" },
      { day: "2", description: "Día Nacional del Bombero Voluntario de la República Argentina", type: "event" },
      { day: "3", description: "#NI UNA MENOS - Día de la acción colectiva contra los femicidios", type: "event" },
      { day: "5", description: "Día Mundial del Medio Ambiente", type: "event" },
      { day: "6", description: "Día del Periodista (7-6)", type: "event" },
      { day: "9-13", description: "Semana de la producción escrita", type: "event" },
      { day: "10", description: "Día de la Seguridad Vial en la Argentina", type: "event" },
      { day: "10", description: "Día de la Afirmación de los Derechos Argentinos sobre las Malvinas, Islas y sector antártico", type: "event" },
      { day: "11", description: "Aniversario del Nacimiento de Manuel Dorrego", type: "event" },
      { day: "12", description: "Día Mundial contra el Trabajo Infantil", type: "event" },
      { day: "12", description: "Día de las y los Adolescentes y Jóvenes por la Inclusión Social y la Convivencia contra Toda Forma de Violencia y Discriminación", type: "event" },
      { day: "13", description: "Día del Libro (15-6)", type: "event" },
      { day: "13", description: "Conmemoración de la Reforma Universitaria de 1918 (15-6)", type: "event" },
      { day: "16", description: "Día Nacional de la Libertad Latinoamericana", type: "holiday" },
      { day: "17", description: "Día Nacional de la Libertad Latinoamericana, en conmemoración del fallecimiento del Gral. Martín Miguel Juan de Mata Güemes", type: "event" },
      { day: "19", description: "Día de la Bandera (20-6)", type: "event" },
      { day: "20", description: "Paso a la inmortalidad del Gral. Manuel Belgrano", type: "holiday" },
      { day: "23", description: "Año Nuevo de los Pueblos Originarios (21/6)", type: "event" },
      { day: "23", description: "Día de la Confraternidad Antártica (21-6)", type: "event" },
      { day: "23", description: "Día de la Ancianidad (21-6)", type: "event" },
      { day: "26", description: "Natalicio de Juana Manso", type: "event" },
      { day: "30", description: "Día de la Prefectura Naval Argentina", type: "event" },
      { day: "30 al 4/7", description: "2da semana de convivencia Escolar", type: "event" },
    ],
  },
  {
    month: "Julio",
    events: [
      { day: "4", description: "Día Internacional del Cooperativismo (5-7)", type: "event" },
      { day: "7-11", description: "Semana de la Independencia", type: "event" },
      { day: "7", description: "Día de la Conservación del Suelo", type: "event" },
      { day: "8", description: "Día de la Independencia (9-7)", type: "event" },
      { day: "9", description: "Día de la Independencia", type: "holiday" },
      { day: "11", description: "Día de la confraternidad argentino- boliviana (12-7)", type: "event" },
      { day: "11", description: "Día Nacional de la Medicina Social", type: "event" },
      { day: "11", description: "Día de los Intereses Argentinos en el Mar", type: "event" },
      { day: "18", description: "Jornada de Reflexión Atentado a la AMIA", type: "event" },
      { day: "21 al 1/8", description: "Receso escolar de invierno", type: "recess" },
    ],
  },
  {
    month: "Agosto",
    events: [
      { day: "1-8", description: "Semana Mundial de la Lactancia Materna", type: "event" },
      { day: "1", description: "Día de la Escuela Pública, Digna y Segura (2-8)", type: "event" },
      { day: "6", description: "Día de la Educación Agropecuaria", type: "event" },
      { day: "8", description: "Día de la Educación Especial (9-8)", type: "event" },
      { day: "8", description: "Segunda Jornada Leer en Comunidad", type: "event" },
      { day: "8", description: "Día de la Fuerza Aérea (10-8)", type: "event" },
      { day: "11-15", description: "Semana Sanmartiniana", type: "event" },
      { day: "11-15", description: "Semana de celebración del “Día de las niñeces”", type: "event" },
      { day: "11", description: "Día Bonaerense de las Niñas y Mujeres en la Ciencia", type: "event" },
      { day: "14", description: "Día de las niñeces (17-8)", type: "event" },
      { day: "15", description: "Día no laborable con fines turísticos", type: "holiday" },
      { day: "18", description: "Conmemoración del aniversario de la muerte del Gral. José de San Martín (17-8)", type: "event" },
      { day: "18-29", description: "Mes del Árbol", type: "event" },
      { day: "22", description: "Día del Folklore", type: "event" },
      { day: "26-30", description: "Semana de la Educación Sexual Integral (ESI)", type: "event" },
      { day: "26", description: "Día Internacional contra el Dengue", type: "event" },
      { day: "29", description: "Día Internacional del Desaparecido (30-8)", type: "event" },
    ],
  },
  {
    month: "Septiembre",
    events: [
      { day: "1-5", description: "Semana de la Industria y el Trabajo Argentino", type: "event" },
      { day: "2", description: "Día de la Industria Nacional", type: "event" },
      { day: "4", description: "Día del Inmigrante", type: "event" },
      { day: "5", description: "Día de la Recuperación de la Educación Técnica (7-9)", type: "event" },
      { day: "8-12", description: "Semana de la Educación", type: "event" },
      { day: "8", description: "Día Internacional de la Alfabetización", type: "event" },
      { day: "11", description: "Día de la maestra y el maestro", type: "holiday" },
      { day: "12", description: "Día del Bibliotecario y la Bibliotecaria (13-8)", type: "event" },
      { day: "15-19", description: "Semana de la participación estudiantil", type: "event" },
      { day: "15-19", description: "Semana de la Donación de Órganos", type: "event" },
      { day: "16", description: "Día de la Reafirmación de los Derechos del Estudiante Secundario. Día Nacional de la Juventud", type: "event" },
      { day: "17", description: "Día de las Profesoras y los Profesores", type: "event" },
      { day: "19", description: "Día de las Preceptoras y los Preceptores", type: "event" },
      { day: "19", description: "Día de la Recreación (21-9)", type: "event" },
      { day: "19", description: "Día de las y los estudiantes (21-9)", type: "event" },
      { day: "19", description: "Día de la Paz (21-9)", type: "event" },
      { day: "22-24", description: "Año Nuevo Judío", type: "holiday" },
      { day: "22 al 3/10", description: "Semanas de las Artes", type: "event" },
      { day: "23", description: "Día Internacional contra la Trata de Mujeres, Niños y Niñas", type: "event" },
      { day: "23", description: "Día del Voto Femenino", type: "event" },
      { day: "23", description: "Día de la Lucha contra las Adicciones", type: "event" },
      { day: "26", description: "Día Nacional de los Derechos del Niño, la Niña y Adolescentes (27-9)", type: "event" },
      { day: "26", description: "Día Nacional de la Conciencia Ambiental (27-9)", type: "event" },
      { day: "29 al 3/10", description: "3er semana de convivencia Escolar", type: "event" },
    ],
  },
  {
    month: "Octubre",
    events: [
      { day: "1-2", description: "Día del Perdón (judaísmo)", type: "holiday" },
      { day: "2", description: "Día Internacional de la No Violencia", type: "event" },
      { day: "2", description: "Homenaje a Marcos Sastre", type: "event" },
      { day: "2", description: "Día Provincial de la concientización de la Dislexia y las Dificultades Específicas del Aprendizaje", type: "event" },
      { day: "3", description: "Día del Camino y de la Educación Vial (5-10)", type: "event" },
      { day: "6-10", description: "Semana de la Investigación Científica", type: "event" },
      { day: "8", description: "Día Provincial del Conocimiento Científico", type: "event" },
      { day: "8", description: "Día Nacional del Estudiante Solidario", type: "event" },
      { day: "10", description: "Día mundial de la Salud Mental", type: "event" },
      { day: "10", description: "Día del Respeto a la Diversidad Cultural (12-10)", type: "event" },
      { day: "10", description: "Día de Reducción de Riesgos de Desastres (13-10)", type: "event" },
      { day: "12", description: "Día del respeto a la diversidad cultural", type: "holiday" },
      { day: "14-17", description: "Semana de América Latina", type: "event" },
      { day: "15", description: "Día de la Cooperación Escolar", type: "event" },
      { day: "17", description: "120 años de la Ley Nacional (4874/1905) conocida como la Ley Lainez", type: "event" },
      { day: "17", description: "Día de la Participación Popular", type: "event" },
      { day: "20-24", description: "Semana de la Educación Física", type: "event" },
      { day: "22", description: "Día Nacional del Derecho a la Identidad", type: "event" },
      { day: "24", description: "Día Internacional contra el Cambio Climático", type: "event" },
      { day: "24", description: "Día de las Naciones Unidas (ONU)", type: "event" },
      { day: "29", description: "Aniversario de la Fundación de la Base Aérea Vicecomodoro Marambio", type: "event" },
      { day: "30", description: "Día de la Recuperación de la Democracia", type: "event" },
    ],
  },
  {
    month: "Noviembre",
    events: [
      { day: "3-7", description: "Semana de la Geografía Argentina", type: "event" },
      { day: "3", description: "Día de los Muertos por la Patria y del Soldado Desconocido (2-11)", type: "event" },
      { day: "4", description: "Día de la Unidad de los Pueblos de América del Sur", type: "event" },
      { day: "6", description: "Día del Comercio", type: "event" },
      { day: "7", description: "Día Mundial del Urbanismo (8-11)", type: "event" },
      { day: "7", description: "Día Nacional de los/las afroargentinos/as y de la cultura afro (8-11)", type: "event" },
      { day: "7", description: "Día Nacional de la/el Donante Voluntario/a de Sangre (9-11)", type: "event" },
      { day: "10", description: "Día de la Tradición", type: "event" },
      { day: "13", description: "Día del Pensamiento Nacional", type: "event" },
      { day: "14", description: "Día de homenaje a las y los tripulantes del submarino ARA San Juan (15-11)", type: "event" },
      { day: "14", description: "Día de la Educación Técnica (15-11)", type: "event" },
      { day: "14", description: "Día Mundial sin alcohol (15-11)", type: "event" },
      { day: "19", description: "Día de la Soberanía Nacional (20-11)", type: "event" },
      { day: "19", description: "Día de la Bandera Bonaerense (20-11)", type: "event" },
      { day: "19", description: "Día Mundial para la Prevención del Abuso Infantil", type: "event" },
      { day: "20", description: "Día de la Soberanía Nacional", type: "holiday" },
      { day: "21", description: "Día no laborable con fines turísticos", type: "holiday" },
      { day: "24", description: "Día de la Flor Nacional (22-11)", type: "event" },
      { day: "24", description: "Día de la Música (22-11)", type: "event" },
      { day: "24", description: "Día de la Defensa Civil (23-11)", type: "event" },
      { day: "25", description: "Día Internacional de la No Violencia", type: "event" },
      { day: "27", description: "Día de la Educación de Adultos Bonaerense", type: "event" },
      { day: "28", description: "Finalización del Ciclo Lectivo de Institutos dependientes de la Dirección de Educación Superior", type: "event" },
      { day: "28", description: "Día de los Consejos Escolares de la provincia de Buenos Aires (29-11)", type: "event" },
    ],
  },
  {
    month: "Diciembre",
    events: [
      { day: "1-5", description: "Semana de la Tecnología", type: "event" },
      { day: "1", description: "Día Internacional de la lucha contra el SIDA", type: "event" },
      { day: "8", description: "Día de la Inmaculada Concepción de María", type: "holiday" },
      { day: "10", description: "Día Internacional de la Declaración de los Derechos Humanos", type: "event" },
      { day: "10", description: "Día de la Restauración de la Democracia", type: "event" },
      { day: "10", description: "Aniversario de la entrega del Premio Nobel de Química al Dr. Luis Federico Leloir", type: "event" },
      { day: "11", description: "Día Nacional del tango", type: "event" },
      { day: "16", description: "Resolución N° 2065 de la Asamblea General de Naciones Unidas sobre Malvinas", type: "event" },
      { day: "22", description: "Finalización del Ciclo Lectivo", type: "event" },
      { day: "25", description: "Navidad", type: "holiday" },
    ],
  },
];
